# === JANELA =====================================
[main]
font=JetBrainsMono Nerd Font:size=13
dpi-aware=auto
width=30%
lines=8
prompt=  
anchor=center
x-margin=0
y-margin=0

# === CORES ======================================
[colors]
background=1d1d20e6
text=ffffffff
match=a0a0a0ff
selection=2a2a2eff
selection-text=ffffffff
selection-match=ffffffff
border=a0a0a033

# === BORDA ======================================
[border]
width=1
radius=8

# === ÍCONES =====================================
[dmenu]
exit-immediately-if-empty=yes
