# Gerado por theme-set.sh — NÃO editar à mão, sobrescrito a cada troca de tema.
set -g @tmux_power_theme '#8a8a8d'
set -g @tmux_power_g0 "#0f0f10"
set -g @tmux_power_g1 "#18181b"
set -g @tmux_power_g2 "#252529"
set -g @tmux_power_g3 "#9a9996"
set -g @tmux_power_g4 "#f0f0f0"
set -g window-style "fg=#deddda,bg=default"
set -g window-active-style "fg=#deddda,bg=default"
set -g cursor-colour "#deddda"
