# === JANELA =====================================
[main]
font=JetBrainsMono Nerd Font:size=13
dpi-aware=auto
width=35
lines=8
prompt=>
anchor=center
x-margin=0
y-margin=0

# === TEMA (cores) — gerado por theme-set.sh, ver themes/ no root do repo ===
include=~/.config/fuzzel/colors.ini

# === BORDA ======================================
[border]
width=1
radius=8

# === ÍCONES =====================================
[dmenu]
exit-immediately-if-empty=yes
