# === GERAL =====================================
general {
  disable_loading_bar = true
  hide_cursor = false
  grace = 0
  no_fade_in = false
}

# === BACKGROUND ================================
background {
  monitor =
  path = screenshot   # tira screenshot da tela atual
  blur_passes = 3
  blur_size = 7
  brightness = 0.6
  contrast = 1.0
  noise = 0.02
}

# === INPUT FIELD (senha) =======================
input-field {
  monitor =
  size = 280, 48
  outline_thickness = 1
  dots_size = 0.25
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba(a0a0a033)
  inner_color = rgba(1d1d20ee)
  font_color = rgb(ffffff)
  fade_on_empty = true
  placeholder_text = <span foreground="##a0a0a0"> senha...</span>
  hide_input = false
  check_color = rgba(a0a0a0ff)
  fail_color = rgba(ff6464ff)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = rgba(ffcc00ff)
  position = 0, -100
  halign = center
  valign = center
}

# === HORA ======================================
label {
  monitor =
  text = $TIME
  color = rgba(ffffffff)
  font_size = 64
  font_family = JetBrainsMono Nerd Font
  position = 0, 200
  halign = center
  valign = center
}

# === DATA ======================================
label {
  monitor =
  text = cmd[update:60000] date +"%A, %d de %B"
  color = rgba(a0a0a0ff)
  font_size = 18
  font_family = JetBrainsMono Nerd Font
  position = 0, 130
  halign = center
  valign = center
}

# === USUÁRIO ===================================
label {
  monitor =
  text =  $USER
  color = rgba(a0a0a0ff)
  font_size = 14
  font_family = JetBrainsMono Nerd Font
  position = 0, -48
  halign = center
  valign = center
}

# === ATIVIDADE ==================================

bindl = , switch:on:Lid Switch, exec, hyprlock

listener {
  timeout = 300          # 5 minutos
  on-timeout = hyprlock
}