[terminal]
vt = 1

[default_session]
command = "tuigreet --time --remember --remember-session --sessions /usr/share/wayland-sessions --theme 'border=#a0a0a0;text=#ffffff;prompt=#a0a0a0;time=#ffffff;action=#a0a0a0;button=#a0a0a0;container=#1d1d20;input=#ffffff;title=#a0a0a0;greet=#ffffff'"
user = "greetd"
