[General]
DisplayServer=wayland
Numlock=on

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=JetBrainsMono Nerd Font

[Users]
RememberLastSession=true
RememberLastUser=true

[Wayland]
SessionDir=/usr/share/wayland-sessions
